sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: password
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LARR5tPeFLzsPPT8gG3LPW88
    access-key-secret: U6k1brOZ8gaOIXv2nXbulGTUzy6Wd9
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    #    password: 123456
    database: 0
    # database默認為1
  wechat:
    appid: wx5e3dde9d5df9df58
    secret: 7a468c0cab2186281c18839acf453e37
    mchid: 1561414865
    mchSerialNo: 4B3B3DC48564AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK55478435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php